name: PinPassword
version: '1.2-fix'
main: ru.vanamxd.pinpassword.PinPlugin
api-version: '1.16'
author: vanamxd
softdepend:
  - PlaceholderAPI
commands:
  pin:
permissions:
  pinpassword.required:
    default: false